version: "3.7"

services:
  node-red:
    image: node
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "21880:1880"
    entrypoint: "/opt/data/entrypoint.sh"
    environment: 
      - NODE_RED_STARTUP_DIR=/data
    volumes:
      - ./data/settings.js:/opt/data/settings.js
      - ./data/flows_cred.json:/opt/data/flows_cred.json
      - ./data/flows.json:/opt/data/flows.json
      - ./data/package.json:/opt/data/package.json
      - ./data/node-red-user-dir:/opt/data/node-red-user-dir
      - ./data/entrypoint.sh:/opt/data/entrypoint.sh
      - ./data/backup.sh:/opt/data/backup.sh